import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');
const soundsDir = join(rootDir, 'assets', 'sounds');
const outputFile = join(rootDir, 'src', 'sounds.generated.ts');

function getOggFiles(dir) {
    try {
        return readdirSync(dir)
            .filter(f => f.endsWith('.ogg'))
            .sort();
    } catch {
        return [];
    }
}

function fileToBase64(filePath) {
    const buffer = readFileSync(filePath);
    return buffer.toString('base64');
}

const pageFlipFiles = getOggFiles(join(soundsDir, 'page-flip'));
const newNoteFiles = getOggFiles(join(soundsDir, 'new-note'));

const pageFlipSounds = pageFlipFiles.map(f =>
    fileToBase64(join(soundsDir, 'page-flip', f))
);

const newNoteSounds = newNoteFiles.map(f =>
    fileToBase64(join(soundsDir, 'new-note', f))
);

const output = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/generate-sounds.mjs

export const PAGE_FLIP_SOUNDS: string[] = [
${pageFlipSounds.map(s => `    "${s}",`).join('\n')}
];

export const NEW_NOTE_SOUNDS: string[] = [
${newNoteSounds.map(s => `    "${s}",`).join('\n')}
];
`;

writeFileSync(outputFile, output);
console.log(`Generated ${outputFile}`);
console.log(`  - ${pageFlipSounds.length} page-flip sounds`);
console.log(`  - ${newNoteSounds.length} new-note sounds`);
